server:
  port: 8888

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teste
    username: root
    password: example
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
      cache: false

